# Generated by Django 5.2.7 on 2025-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('admin', 'Админ')], default='student', max_length=20),
        ),
    ]
