# Generated by Django 6.0 on 2026-09-08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('order', 'id')},
        ),
    ]
