# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('users', '0004_alter_customuser_id')]

    operations = [
        migrations.RemoveField(model_name='customuser', name='phone_number'),
    ]
